[package]
name = "pomme-synth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.2.1"
rtrb = "0.2.1" # tmp?

# debug
log = "0.4.14"

# GUI

baseview = { git = "https://github.com/rustaudio/baseview.git", rev = "004065e9a43e79751040879c572d95b9b63e0edc" }
raw-window-handle = { version = "0.4" }

[lib]
name = "pomme_synth_vst"
crate-type = ["cdylib"]

